apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-r0v9pn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-r0v9pn
  namespace: my-nginx-r0v9pn
  labels:
    name: nginx-r0v9pn
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-r0v9pn
  template:
    metadata:
      namespace: my-nginx-r0v9pn
      labels:
        name: nginx-r0v9pn
    spec:
      containers:
      - name: nginx-r0v9pn
        image: nginx
        ports:
        - containerPort: 80

